---
# tasks file for ec2-vpc

- import_tasks: create.yml
  when: vpc_action == 'create'

- import_tasks: igw.yml
- import_tasks: routing.yml

- import_tasks: nat.yml
  when: create_nat_gw is defined and new_vpc.igw and vpc_action == 'create'

- import_tasks: remove.yml
  when: vpc_action == 'remove'
