---

- name: Create routing tables for new VPC
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    purge_subnets: false
    purge_routes: false
    tags:
      Name: "{{ vpc_name }} {{ item }} Routing Table"
      VPC: "{{ vpc_name }}"
  with_items:
    - Data
    - Private
