---

- name: Get info about route tables
  ec2_vpc_route_table_facts:
    region: "{{ region }}"
    filters:
      vpc_id: "{{ vpc_id }}"
      "association.main": "true"
  register: new_vpc_rt

- name: Set route table ID in fact
  set_fact:
    vpc_rt_id: "{{ new_vpc_rt.route_tables.0.id }}"

- name: Update new Presentation routing table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    lookup: id
    route_table_id: "{{ vpc_rt_id }}"
    region: "{{ region }}"
    purge_subnets: false
    purge_routes: false
    tags:
      Name: "{{ vpc_name }} Presentation Routing Table"
      VPC: "{{ vpc_name }}"
      Tier: Presentation
      Type: External
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ vpc_igw_id }}"
    subnets: "{{ subnet_ids | default(omit) }}"

